version: "2"

linters:
  default: standard
  enable:
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - durationcheck
    - err113
    - errname
    - errorlint
    - fatcontext
    - gocritic
    - gosec
    - makezero
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - wrapcheck
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
      disable-default-exclusions: true
    nolintlint:
      require-explanation: true
      require-specific: true
